/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDocumentModal: typeof import('./src/components/firestore/AddDocumentModal.vue')['default']
    AddProjectModal: typeof import('./src/components/modals/AddProjectModal.vue')['default']
    BaseModal: typeof import('./src/components/ui/BaseModal.vue')['default']
    BreadcrumbNavigation: typeof import('./src/components/firestore/BreadcrumbNavigation.vue')['default']
    CollectionsList: typeof import('./src/components/firestore/CollectionsList.vue')['default']
    ConfirmationModal: typeof import('./src/components/modals/ConfirmationModal.vue')['default']
    ConnectionWarning: typeof import('./src/components/ConnectionWarning.vue')['default']
    CreateBucketModal: typeof import('./src/components/modals/CreateBucketModal.vue')['default']
    CreateTopicModal: typeof import('./src/components/modals/CreateTopicModal.vue')['default']
    DocumentEditor: typeof import('./src/components/firestore/DocumentEditor.vue')['default']
    DocumentField: typeof import('./src/components/firestore/DocumentField.vue')['default']
    DocumentFieldsEditor: typeof import('./src/components/firestore/DocumentFieldsEditor.vue')['default']
    DocumentsList: typeof import('./src/components/firestore/DocumentsList.vue')['default']
    FieldEditor: typeof import('./src/components/firestore/FieldEditor.vue')['default']
    FieldFormComponent: typeof import('./src/components/firestore/FieldFormComponent.vue')['default']
    FieldModal: typeof import('./src/components/firestore/FieldModal.vue')['default']
    FieldRenderer: typeof import('./src/components/firestore/FieldRenderer.vue')['default']
    GlobalSearch: typeof import('./src/components/search/GlobalSearch.vue')['default']
    ImportComponent: typeof import('./src/components/import-export/ImportComponent.vue')['default']
    JsonFieldEditor: typeof import('./src/components/firestore/JsonFieldEditor.vue')['default']
    JsonNode: typeof import('./src/components/firestore/JsonNode.vue')['default']
    KeyValueInput: typeof import('./src/components/ui/KeyValueInput.vue')['default']
    MessageAttributeInput: typeof import('./src/components/ui/MessageAttributeInput.vue')['default']
    NavItem: typeof import('./src/components/navigation/NavItem.vue')['default']
    NestedFieldRenderer: typeof import('./src/components/firestore/NestedFieldRenderer.vue')['default']
    ProjectSelector: typeof import('./src/components/navigation/ProjectSelector.vue')['default']
    PublishMessageModal: typeof import('./src/components/modals/PublishMessageModal.vue')['default']
    RecursiveFieldViewer: typeof import('./src/components/firestore/RecursiveFieldViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartCollectionModal: typeof import('./src/components/firestore/StartCollectionModal.vue')['default']
    SubcollectionView: typeof import('./src/components/firestore/SubcollectionView.vue')['default']
    SubscriptionMessagesModal: typeof import('./src/components/modals/SubscriptionMessagesModal.vue')['default']
    SuccessNotification: typeof import('./src/components/ui/SuccessNotification.vue')['default']
    TemplateVariableInput: typeof import('./src/components/ui/TemplateVariableInput.vue')['default']
    TopicDetailsModal: typeof import('./src/components/modals/TopicDetailsModal.vue')['default']
  }
}
