/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddProjectModal: typeof import('./src/components/modals/AddProjectModal.vue')['default']
    BaseModal: typeof import('./src/components/ui/BaseModal.vue')['default']
    ConfirmationModal: typeof import('./src/components/modals/ConfirmationModal.vue')['default']
    ConnectionWarning: typeof import('./src/components/ConnectionWarning.vue')['default']
    CreateBucketModal: typeof import('./src/components/modals/CreateBucketModal.vue')['default']
    CreateTopicModal: typeof import('./src/components/modals/CreateTopicModal.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogPanel: typeof import('@headlessui/vue')['DialogPanel']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    GlobalSearch: typeof import('./src/components/search/GlobalSearch.vue')['default']
    KeyValueInput: typeof import('./src/components/ui/KeyValueInput.vue')['default']
    MessageAttributeInput: typeof import('./src/components/ui/MessageAttributeInput.vue')['default']
    NavItem: typeof import('./src/components/navigation/NavItem.vue')['default']
    ProjectSelector: typeof import('./src/components/navigation/ProjectSelector.vue')['default']
    PublishMessageModal: typeof import('./src/components/modals/PublishMessageModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscriptionMessagesModal: typeof import('./src/components/modals/SubscriptionMessagesModal.vue')['default']
    TemplateVariableInput: typeof import('./src/components/ui/TemplateVariableInput.vue')['default']
    TopicDetailsModal: typeof import('./src/components/modals/TopicDetailsModal.vue')['default']
  }
}
