name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major

concurrency:
  group: "release"
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: drehelis/improved-chainsaw/.github/workflows/release.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      timeout_minutes: 5
    secrets: inherit
